/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Pieces for Developers",
  "tagline": "Learn how to best use and optimize your workflow with Pieces for Developers!",
  "favicon": "assets/pieces_logos/white_circle.png",
  "url": "https://docs.pieces.app",
  "baseUrl": "/",
  "organizationName": "pieces-app",
  "projectName": "documentation",
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "throw",
  "onBrokenMarkdownLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "@gracefullight/docusaurus-plugin-vercel-analytics"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs",
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/pieces-app/documentation/tree/main/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "googleTagManager": {
          "containerId": "GTM-K8C6QWB"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.8,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "assets/pfd_preview.png",
    "metadata": [
      {
        "name": "og:image",
        "content": "assets/pfd_preview.png"
      }
    ],
    "announcementBar": {
      "id": "new-docs",
      "content": "🚀 Welcome to the new Pieces for Developers Documentation! 🚀",
      "isCloseable": true
    },
    "algolia": {
      "appId": "KTOXFODR65",
      "apiKey": "ea4804560699e4b727715163b74bea83",
      "indexName": "pieces_docusaurus",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "logo": {
        "alt": "Pieces for Developers",
        "src": "assets/pieces_logos/wordmark.svg",
        "srcDark": "assets/pieces_logos/white_wordmark.svg",
        "href": "https://pieces.app"
      },
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "right"
        },
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "label": "Learn",
          "position": "right"
        },
        {
          "to": "/community",
          "label": "Community",
          "position": "right"
        },
        {
          "to": "/support",
          "label": "Support",
          "position": "right"
        },
        {
          "to": "/faq",
          "label": "FAQ",
          "position": "right"
        },
        {
          "href": "https://github.com/pieces-app/documentation",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Socials",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/getpieces"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/getpieces"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/getpieces"
            },
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/@getpieces"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/getpieces"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Blog",
              "href": "https://code.pieces.app/blog"
            },
            {
              "label": "Product Updates",
              "href": "https://code.pieces.app/updates"
            },
            {
              "label": "Press",
              "href": "https://news.pieces.app"
            },
            {
              "label": "Newsletter",
              "href": "https://thepiecespost.beehiiv.com"
            }
          ]
        },
        {
          "title": "Terms & Policies",
          "items": [
            {
              "label": "Privacy Policy",
              "href": "/privacy-policy"
            },
            {
              "label": "Terms of Service",
              "href": "/terms"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Mesh Intelligent Technologies, Inc. All rights reserved.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
